apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blueprint
nameSuffix: -secondary

commonLabels:
  region: secondary
  failover: "true"

resources:
  - ../episode-generation-job.yaml
  - ../genie-sim-gpu-job.yaml
  - ../dream2flow-preparation-job.yaml
  - ../dwm-preparation-job.yaml
